In [1]:
import pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Train.csv')
df2 = pd.read_csv('Test.csv')

In [3]:
df.head()

,Place_ID X Date,Date,Place_ID,target,target_min,target_max,target_variance,target_count,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
0,010Q650 X 2020-01-02,2020-01-02,010Q650,38.0,23.0,53.0,769.50,92,11.000000,60.200001,...,38.593017,-61.752587,22.363665,1793.793579,3227.855469,0.010579,74.481049,37.501499,-62.142639,22.545118
1,010Q650 X 2020-01-03,2020-01-03,010Q650,39.0,25.0,63.0,1319.85,91,14.600000,48.799999,...,59.624912,-67.693509,28.614804,1789.960449,3384.226562,0.015104,75.630043,55.657486,-53.868134,19.293652
2,010Q650 X 2020-01-04,2020-01-04,010Q650,24.0,8.0,56.0,1181.96,96,16.400000,33.400002,...,49.839714,-78.342701,34.296977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010Q650 X 2020-01-05,2020-01-05,010Q650,49.0,10.0,55.0,1113.67,96,6.911948,21.300001,...,29.181258,-73.896588,30.545446,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010Q650 X 2020-01-06,2020-01-06,010Q650,21.0,9.0,52.0,1164.82,95,13.900001,44.700001,...,0.797294,-68.612480,26.899694,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df2

,Place_ID X Date,Date,Place_ID,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
0,0OS9LVX X 2020-01-02,2020-01-02,0OS9LVX,11.600000,30.200001,0.00409,14.656824,3.956377,0.712605,0.000053,...,1.445658,-95.984984,22.942019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0OS9LVX X 2020-01-03,2020-01-03,0OS9LVX,18.300001,42.900002,0.00595,15.026544,4.230430,0.661892,0.000050,...,34.641758,-95.014908,18.539116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0OS9LVX X 2020-01-04,2020-01-04,0OS9LVX,17.600000,41.299999,0.00590,15.511041,5.245728,1.640559,0.000050,...,55.872276,-94.015418,14.140820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0OS9LVX X 2020-01-05,2020-01-05,0OS9LVX,15.011948,53.100002,0.00709,14.441858,5.454001,-0.190532,0.000055,...,59.174188,-97.247602,32.730553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0OS9LVX X 2020-01-06,2020-01-06,0OS9LVX,9.700000,71.599998,0.00808,11.896295,3.511787,-0.279441,0.000055,...,40.925873,-96.057265,28.320527,1831.261597,3229.118652,0.031068,-100.278343,41.84708,-95.910744,28.498789

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30557 entries, 0 to 30556
Data columns (total 82 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      30557 non-null  object
 1   Date                                                 30557 non-null  object
 2   Place_ID                                             30557 non-null  object
 3   target                                               30557 non-null  float64
 4   target_min                                           30557 non-null  float64
 5   target_max                                           30557 non-null  float64
 6   target_variance                                      30557 non-null  float64
 7   target_count                                         30557 non-null  int64
 8   precipitable_water_entire_atmosphere                 30557 non-null  float64
 9   relative_humidity_2m_above_ground                    30557 non-null  float64
 10  specific_humidity_2m_above_ground                    30557 non-null  float64
 11  temperature_2m_above_ground                          30557 non-null  float64
 12  u_component_of_wind_10m_above_ground                 30557 non-null  float64
 13  v_component_of_wind_10m_above_ground                 30557 non-null  float64
 14  L3_NO2_NO2_column_number_density                     28368 non-null  float64
 15  L3_NO2_NO2_slant_column_number_density               28368 non-null  float64
 16  L3_NO2_absorbing_aerosol_index                       28368 non-null  float64
 17  L3_NO2_cloud_fraction                                28368 non-null  float64
 18  L3_NO2_sensor_altitude                               28368 non-null  float64
 19  L3_NO2_sensor_azimuth_angle                          28367 non-null  float64
 20  L3_NO2_sensor_zenith_angle                           28367 non-null  float64
 21  L3_NO2_solar_azimuth_angle                           28367 non-null  float64
 22  L3_NO2_solar_zenith_angle                            28367 non-null  float64
 23  L3_NO2_stratospheric_NO2_column_number_density       28367 non-null  float64
 24  L3_NO2_tropopause_pressure                           28367 non-null  float64
 25  L3_NO2_tropospheric_NO2_column_number_density        21888 non-null  float64
 26  L3_O3_O3_column_number_density                       30274 non-null  float64
 27  L3_O3_O3_effective_temperature                       30274 non-null  float64
 28  L3_O3_cloud_fraction                                 30274 non-null  float64
 29  L3_O3_sensor_azimuth_angle                           30274 non-null  float64
 30  L3_O3_sensor_zenith_angle                            30274 non-null  float64
 31  L3_O3_solar_azimuth_angle                            30274 non-null  float64
 32  L3_O3_solar_zenith_angle                             30274 non-null  float64
 33  L3_CO_CO_column_number_density                       25134 non-null  float64
 34  L3_CO_H2O_column_number_density                      25134 non-null  float64
 35  L3_CO_cloud_height                                   25134 non-null  float64
 36  L3_CO_sensor_altitude                                25134 non-null  float64
 37  L3_CO_sensor_azimuth_angle                           25134 non-null  float64
 38  L3_CO_sensor_zenith_angle                            25134 non-null  float64
 39  L3_CO_solar_azimuth_angle                            25134 non-null  float64
 40  L3_CO_solar_zenith_angle                             25134 non-null  float64
 41  L3_HCHO_HCHO_slant_column_number_density             23132 non-null  float64
 42  L3_HCHO_cloud_fraction                               23132 non-null  float64
 43  L3_HCHO_sensor_azimuth_angle                         23132 non-null  float64
 44  L3_HCHO_sensor_zenith_angle                          23132 non-null  float64
 45  L3_HCHO_solar_azimuth_angle                          23132 non-null  float64
 46  L3_HCHO_solar_zenith_angle                           23132 non-null  float64
 47  L3_HCHO_tropospheric_HCHO_column_number_density      23132 non-null  float64
 48  L3_HCHO_tropospheric_HCHO_column_number_density_amf  23132 non-null  float64
 49  L3_CLOUD_cloud_base_height                           29035 non-null  float64
 50  L3_CLOUD_cloud_base_pressure                         29035 non-null  float64
 51  L3_CLOUD_cloud_fraction                              30183 non-null  float64
 52  L3_CLOUD_cloud_optical_depth                         29035 non-null  float64
 53  L3_CLOUD_cloud_top_height                            29035 non-null  float64
 54  L3_CLOUD_cloud_top_pressure                          29035 non-null  float64
 55  L3_CLOUD_sensor_azimuth_angle                        30183 non-null  float64
 56  L3_CLOUD_sensor_zenith_angle                         30183 non-null  float64
 57  L3_CLOUD_solar_azimuth_angle                         30183 non-null  float64
 58  L3_CLOUD_solar_zenith_angle                          30183 non-null  float64
 59  L3_CLOUD_surface_albedo                              29035 non-null  float64
 60  L3_AER_AI_absorbing_aerosol_index                    30360 non-null  float64
 61  L3_AER_AI_sensor_altitude                            30360 non-null  float64
 62  L3_AER_AI_sensor_azimuth_angle                       30360 non-null  float64
 63  L3_AER_AI_sensor_zenith_angle                        30360 non-null  float64
 64  L3_AER_AI_solar_azimuth_angle                        30360 non-null  float64
 65  L3_AER_AI_solar_zenith_angle                         30360 non-null  float64
 66  L3_SO2_SO2_column_number_density                     23320 non-null  float64
 67  L3_SO2_SO2_column_number_density_amf                 23320 non-null  float64
 68  L3_SO2_SO2_slant_column_number_density               23320 non-null  float64
 69  L3_SO2_absorbing_aerosol_index                       23249 non-null  float64
 70  L3_SO2_cloud_fraction                                23320 non-null  float64
 71  L3_SO2_sensor_azimuth_angle                          23320 non-null  float64
 72  L3_SO2_sensor_zenith_angle                           23320 non-null  float64
 73  L3_SO2_solar_azimuth_angle                           23320 non-null  float64
 74  L3_SO2_solar_zenith_angle                            23320 non-null  float64
 75  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        5792 non-null   float64
 76  L3_CH4_aerosol_height                                5792 non-null   float64
 77  L3_CH4_aerosol_optical_depth                         5792 non-null   float64
 78  L3_CH4_sensor_azimuth_angle                          5792 non-null   float64
 79  L3_CH4_sensor_zenith_angle                           5792 non-null   float64
 80  L3_CH4_solar_azimuth_angle                           5792 non-null   float64
 81  L3_CH4_solar_zenith_angle                            5792 non-null   float64
dtypes: float64(78), int64(1), object(3)
memory usage: 19.1+ MB

In [6]:
df['Date'] = pd.to_datetime(df['Date'])

In [7]:
#dropping all columns and rows with more than 70% NA Values
print('Shape Before Dropping', df.shape)
df.dropna(axis=1, thresh=int(0.3 * df.shape[0]), inplace=True)
df.dropna(axis=0, thresh=int(0.3 * df.shape[1]), inplace=True)
print('Shape After Dropping', df.shape)

Shape Before Dropping (30557, 82)
Shape After Dropping (30398, 75)

In [8]:
#printing all columns with na values, with their corresponding datatype
cols_with_na = df.columns[(1 - df.count()/df.shape[0]) > 0]
df[cols_with_na].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30398 entries, 0 to 30555
Data columns (total 61 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   L3_NO2_NO2_column_number_density                     28367 non-null  float64
 1   L3_NO2_NO2_slant_column_number_density               28367 non-null  float64
 2   L3_NO2_absorbing_aerosol_index                       28367 non-null  float64
 3   L3_NO2_cloud_fraction                                28367 non-null  float64
 4   L3_NO2_sensor_altitude                               28367 non-null  float64
 5   L3_NO2_sensor_azimuth_angle                          28367 non-null  float64
 6   L3_NO2_sensor_zenith_angle                           28367 non-null  float64
 7   L3_NO2_solar_azimuth_angle                           28367 non-null  float64
 8   L3_NO2_solar_zenith_angle                            28367 non-null  float64
 9   L3_NO2_stratospheric_NO2_column_number_density       28367 non-null  float64
 10  L3_NO2_tropopause_pressure                           28367 non-null  float64
 11  L3_NO2_tropospheric_NO2_column_number_density        21888 non-null  float64
 12  L3_O3_O3_column_number_density                       30274 non-null  float64
 13  L3_O3_O3_effective_temperature                       30274 non-null  float64
 14  L3_O3_cloud_fraction                                 30274 non-null  float64
 15  L3_O3_sensor_azimuth_angle                           30274 non-null  float64
 16  L3_O3_sensor_zenith_angle                            30274 non-null  float64
 17  L3_O3_solar_azimuth_angle                            30274 non-null  float64
 18  L3_O3_solar_zenith_angle                             30274 non-null  float64
 19  L3_CO_CO_column_number_density                       25134 non-null  float64
 20  L3_CO_H2O_column_number_density                      25134 non-null  float64
 21  L3_CO_cloud_height                                   25134 non-null  float64
 22  L3_CO_sensor_altitude                                25134 non-null  float64
 23  L3_CO_sensor_azimuth_angle                           25134 non-null  float64
 24  L3_CO_sensor_zenith_angle                            25134 non-null  float64
 25  L3_CO_solar_azimuth_angle                            25134 non-null  float64
 26  L3_CO_solar_zenith_angle                             25134 non-null  float64
 27  L3_HCHO_HCHO_slant_column_number_density             23132 non-null  float64
 28  L3_HCHO_cloud_fraction                               23132 non-null  float64
 29  L3_HCHO_sensor_azimuth_angle                         23132 non-null  float64
 30  L3_HCHO_sensor_zenith_angle                          23132 non-null  float64
 31  L3_HCHO_solar_azimuth_angle                          23132 non-null  float64
 32  L3_HCHO_solar_zenith_angle                           23132 non-null  float64
 33  L3_HCHO_tropospheric_HCHO_column_number_density      23132 non-null  float64
 34  L3_HCHO_tropospheric_HCHO_column_number_density_amf  23132 non-null  float64
 35  L3_CLOUD_cloud_base_height                           29035 non-null  float64
 36  L3_CLOUD_cloud_base_pressure                         29035 non-null  float64
 37  L3_CLOUD_cloud_fraction                              30183 non-null  float64
 38  L3_CLOUD_cloud_optical_depth                         29035 non-null  float64
 39  L3_CLOUD_cloud_top_height                            29035 non-null  float64
 40  L3_CLOUD_cloud_top_pressure                          29035 non-null  float64
 41  L3_CLOUD_sensor_azimuth_angle                        30183 non-null  float64
 42  L3_CLOUD_sensor_zenith_angle                         30183 non-null  float64
 43  L3_CLOUD_solar_azimuth_angle                         30183 non-null  float64
 44  L3_CLOUD_solar_zenith_angle                          30183 non-null  float64
 45  L3_CLOUD_surface_albedo                              29035 non-null  float64
 46  L3_AER_AI_absorbing_aerosol_index                    30236 non-null  float64
 47  L3_AER_AI_sensor_altitude                            30236 non-null  float64
 48  L3_AER_AI_sensor_azimuth_angle                       30236 non-null  float64
 49  L3_AER_AI_sensor_zenith_angle                        30236 non-null  float64
 50  L3_AER_AI_solar_azimuth_angle                        30236 non-null  float64
 51  L3_AER_AI_solar_zenith_angle                         30236 non-null  float64
 52  L3_SO2_SO2_column_number_density                     23320 non-null  float64
 53  L3_SO2_SO2_column_number_density_amf                 23320 non-null  float64
 54  L3_SO2_SO2_slant_column_number_density               23320 non-null  float64
 55  L3_SO2_absorbing_aerosol_index                       23249 non-null  float64
 56  L3_SO2_cloud_fraction                                23320 non-null  float64
 57  L3_SO2_sensor_azimuth_angle                          23320 non-null  float64
 58  L3_SO2_sensor_zenith_angle                           23320 non-null  float64
 59  L3_SO2_solar_azimuth_angle                           23320 non-null  float64
 60  L3_SO2_solar_zenith_angle                            23320 non-null  float64
dtypes: float64(61)
memory usage: 14.4 MB

In [9]:
#filling the missing values of each feature with its respective mean
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
df[cols_with_na] = imp.fit_transform(df[cols_with_na])

In [10]:
#printing all columns with na values again, with their corresponding datatype, this should give an empty result
cols_with_na = df.columns[(1 - df.count()/df.shape[0]) > 0] 
df[cols_with_na].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30398 entries, 0 to 30555
Empty DataFrame

In [11]:
needed_date_features = ['year', 'month', 'day']
for item in needed_date_features:
    df[item] = getattr(df['Date'].dt, item)

In [12]:
# sns.lineplot(data=df, x="day", y="target")

In [13]:
# sns.lineplot(data=df, x="month", y="target")

In [14]:
target_features = ['target', 'target_min','target_max', 'target_variance', 'target_count']
to_be_removed = ['Place_ID X Date', 'Date', 'Place_ID']
working_df = df.copy()

In [15]:
X = working_df.drop(target_features + to_be_removed, axis=1)
y = working_df['target']

In [16]:
predicting_features = X.columns

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [18]:
# #Working with outliers
# print('before outlier removal', X_train.shape)
# from sklearn.covariance import EllipticEnvelope
# from sklearn.ensemble import IsolationForest
# iso = EllipticEnvelope(contamination=0.01)
# yhat = iso.fit_predict(X_train)
# mask = yhat != -1
# y_train = y_train[mask]
# X_train = X_train[mask]
# print('after outlier removal', X_train.shape)

In [19]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
#Standardizing the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
# #Performing PCA
# from sklearn.decomposition import PCA
# pca = PCA(n_components=70)
# X = pca.fit_transform(X)

In [21]:
# sum(pca.explained_variance_ratio_)

In [22]:
from lightgbm import LGBMRegressor

In [23]:
model = LGBMRegressor(random_state=100)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
prediction_df = pd.DataFrame(data=np.hstack([y_test.values.reshape(-1,1), prediction.reshape(-1,1)]), columns=["Actual Value", "Predicted Value"])
prediction_df.head(10)

   Actual Value  Predicted Value
0          22.0        41.711407
1          26.0        42.137212
2         105.0        59.414115
3         153.0       119.933660
4          27.0        48.451131
5          15.0        33.879738
6          63.0        67.987584
7          15.0        28.430011
8          85.0        67.878371
9          13.0        55.239275

In [25]:
from sklearn.metrics import mean_squared_error

In [26]:
print("MSE Score", mean_squared_error(y_test,prediction))
print("RMSE Score", mean_squared_error(y_test,prediction)**0.5)

MSE Score 1016.454033447914
RMSE Score 31.881876253569423

In [28]:
# df_imp = pd.DataFrame(columns=["label","importance"], data=item_feat_imp).sort_values(by="importance", ascending=False)

NameError: name 'item_feat_imp' is not defined